-- Toastly — diaspora matching rules (PRD §5.6), USD coin packs, and the
-- review console's case model (review-queue / review-case / review-history
-- prototypes).
--
-- PRD §5.6 (decided): ONE Nigeria pool, which members abroad join by choosing
-- "back home" or "Both". Diaspora-to-diaspora is the only separate pool and
-- needs an active Diaspora or Diaspora Plus plan on both sides. Nigeria-based
-- members have "Open to people living abroad" — on by default, a filter on
-- their OWN feed only, never a ranking or scoring input.

-- ---------------------------------------------------------------------------
-- Profiles: a member number for the console, and "open to abroad"
-- ---------------------------------------------------------------------------

-- Reviewers see M-40001, never a name.
alter table public.profiles add column if not exists member_no bigint generated by default as identity (start with 40001);
create unique index if not exists profiles_member_no_key on public.profiles (member_no);

alter table public.profiles add column if not exists open_to_abroad boolean not null default true;
comment on column public.profiles.open_to_abroad is
  'Nigeria-based members only: include members abroad who chose back home in MY six. A filter on the member''s own feed; never a ranking or scoring input (PRD §5.6).';

-- Members can't renumber themselves.
create or replace function public.guard_member_no()
returns trigger language plpgsql set search_path = public as $$
begin
  if current_user in ('authenticated', 'anon') and new.member_no is distinct from old.member_no then
    raise exception 'Member numbers are set by Toastly.' using errcode = '42501';
  end if;
  return new;
end;
$$;
drop trigger if exists guard_member_no on public.profiles;
create trigger guard_member_no before update of member_no on public.profiles
  for each row execute function public.guard_member_no();

-- ---------------------------------------------------------------------------
-- The daily six under §5.6
-- ---------------------------------------------------------------------------

create or replace function public.build_daily_feed(p_profile_id uuid)
returns setof public.daily_feed
language plpgsql
security definer
set search_path = public
as $$
declare
  v_today date := current_date;
  v_tier tier;
  v_pool match_pool;
  v_country text;
  v_open boolean;
  v_city_open boolean;
begin
  if exists (select 1 from daily_feed where profile_id = p_profile_id and feed_date = v_today) then
    return query select * from daily_feed where profile_id = p_profile_id and feed_date = v_today order by position;
    return;
  end if;

  if is_restricted(p_profile_id) then
    return;
  end if;

  select pool, country_code, open_to_abroad into v_pool, v_country, v_open from profiles where id = p_profile_id;
  v_tier := current_tier(p_profile_id);
  v_city_open := diaspora_pool_open(p_profile_id);

  -- Diaspora-to-diaspora is a Diaspora-plan feature. Everyone else draws
  -- from the Nigeria pool, and the pool screen and feed say so.
  if v_tier not in ('diaspora', 'diaspora_plus') then
    v_pool := 'back_home';
    v_city_open := false;
  end if;

  insert into daily_feed (profile_id, feed_date, position, candidate_id)
  select p_profile_id, v_today, row_number() over (), c.id
  from (
    select p.id,
           (
             case when v_tier in ('premium', 'premium_plus', 'diaspora', 'diaspora_plus')
                  then 1.0 else 0.0 end
             + case when p.intent is not distinct from (select intent from profiles where id = p_profile_id)
                    then 0.5 else 0.0 end
             + case when p.city is not distinct from (select city from profiles where id = p_profile_id)
                    then 0.4 else 0.0 end
             + (select count(*) * 0.1 from prompt_answers pa where pa.profile_id = p.id)
             + random() * 0.3
           ) as score
    from profiles p
    where p.id <> p_profile_id
      and p.stage in ('verified_real', 'id_confirmed')
      and p.paused = false
      and not exists (select 1 from account_restrictions r where r.profile_id = p.id and r.lifted_at is null)
      and not exists (select 1 from reverification_requests v where v.profile_id = p.id)
      and (
        -- The Nigeria pool: members in Nigeria, plus — for a Nigeria-based
        -- member who is open to it — members abroad who chose back home.
        (
          (v_pool in ('back_home', 'both') or not v_city_open)
          and (
            p.country_code = 'NG'
            or (v_country = 'NG' and v_open and p.country_code <> 'NG' and p.pool in ('back_home', 'both'))
          )
        )
        -- Diaspora-to-diaspora: both abroad, both chose it, both on a
        -- Diaspora plan, both cities open.
        or (
          v_pool in ('diaspora', 'both')
          and v_city_open
          and p.country_code <> 'NG'
          and p.pool in ('diaspora', 'both')
          and current_tier(p.id) in ('diaspora', 'diaspora_plus')
          and exists (select 1 from diaspora_cities dc where dc.slug = p.diaspora_city and dc.active)
        )
      )
      and not exists (select 1 from seen_candidates s where s.profile_id = p_profile_id and s.candidate_id = p.id)
      and not exists (select 1 from blocks b where (b.blocker_id = p_profile_id and b.blocked_id = p.id)
                                                or (b.blocker_id = p.id and b.blocked_id = p_profile_id))
      --
      -- NOTHING BELOW THIS LINE. Do not add religion, tribe, language,
      -- relationship history, has_children, profession or education to this
      -- WHERE clause. They are display-only and must never silently exclude
      -- anyone from anyone's feed (CLAUDE.md). Opt-in filters belong on the
      -- member's own search, applied to their own results, not here.
      -- Diaspora status is never a score input (PRD §5.6).
      --
    order by score desc
    limit daily_match_count()
  ) c;

  insert into seen_candidates (profile_id, candidate_id)
  select p_profile_id, candidate_id from daily_feed
  where profile_id = p_profile_id and feed_date = v_today
  on conflict do nothing;

  return query select * from daily_feed where profile_id = p_profile_id and feed_date = v_today order by position;
end;
$$;

-- Saving a pool: the diaspora options need a Diaspora plan (the screen shows
-- them as plan-only; the database agrees).
create or replace function public.set_match_pool(p_pool match_pool)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_me uuid := auth.uid();
begin
  if v_me is null then raise exception 'Please sign in again.' using errcode = '42501'; end if;
  if p_pool <> 'back_home' and current_tier(v_me) not in ('diaspora', 'diaspora_plus') then
    raise exception 'Matching within your diaspora comes with a Diaspora plan.' using errcode = '42501';
  end if;
  update profiles set pool = p_pool where id = v_me;
end;
$$;
revoke all on function public.set_match_pool(match_pool) from public, anon;
grant execute on function public.set_match_pool(match_pool) to authenticated;

-- ---------------------------------------------------------------------------
-- Women's offer at signup follows a country given at signup
-- ---------------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_gender text := new.raw_user_meta_data ->> 'gender';
  v_country text := upper(coalesce(new.raw_user_meta_data ->> 'country_code', 'NG'));
begin
  if v_country !~ '^[A-Z]{2}$' then v_country := 'NG'; end if;

  insert into public.profiles (id, display_name, gender, country_code)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'display_name', 'New member'),
    v_gender,
    v_country
  );

  -- Everyone starts on Starter.
  insert into public.entitlements (profile_id, tier, source)
  values (new.id, 'starter', 'default');

  -- Women's launch offer: 30 days of FULL Premium Plus — or Diaspora Plus for
  -- women abroad (PRD §7) — granted automatically, no payment method. If the
  -- country is set later, womens_offer_follows_track (0025) switches it.
  if v_gender = 'woman' then
    insert into public.entitlements (profile_id, tier, source, ends_at)
    values (new.id, case when v_country = 'NG' then 'premium_plus'::tier else 'diaspora_plus'::tier end,
            'womens_launch_offer', now() + interval '30 days');
  end if;

  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- USD coin packs for members abroad (coins-get-usd; decided 4 October 2026)
-- ---------------------------------------------------------------------------

update public.price_list set active = false where sku = 'us-30';
insert into public.price_list (sku, kind, provider, currency, amount_minor, coins, tier, label) values
  ('us-5',  'coin_pack', 'stripe', 'USD',  100,  5, null, '5 coins'),
  ('us-10', 'coin_pack', 'stripe', 'USD',  200, 10, null, '10 coins'),
  ('us-25', 'coin_pack', 'stripe', 'USD',  500, 25, null, '25 coins'),
  ('us-50', 'coin_pack', 'stripe', 'USD', 1000, 50, null, '50 coins')
on conflict (sku) do update set active = true, amount_minor = excluded.amount_minor, coins = excluded.coins;

-- A Naira coin pack bought from a profile abroad is a pricing signal too
-- (members abroad are never quoted naira). Signal only.
create or replace function public.trust_naira_plan_abroad()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_country text;
  v_route text;
begin
  select country_code into v_country from profiles where id = new.profile_id;
  if v_country is null or v_country = 'NG' then return new; end if;
  if tg_table_name = 'payments' then
    if new.currency <> 'NGN' or new.kind not in ('plan_pass', 'plan_recurring', 'plan_remainder', 'coin_pack') then return new; end if;
    v_route := new.kind;
  else
    if new.source <> 'coins' or new.tier not in ('premium', 'premium_plus') then return new; end if;
    v_route := 'coins';
  end if;
  perform _integrity_signal(new.profile_id, 'profile_country_mismatch',
    jsonb_build_object('track', 'ngn', 'route', v_route, 'country', v_country));
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- The review console's case model
-- ---------------------------------------------------------------------------

alter table public.staff_members add column if not exists role text not null default 'Reviewer'
  check (role in ('Reviewer', 'Senior reviewer'));

alter table public.review_items add column if not exists case_no bigint generated by default as identity (start with 20001);
create unique index if not exists review_items_case_no_key on public.review_items (case_no);
alter table public.review_items add column if not exists stage text not null default 'new'
  check (stage in ('new', 'in_review', 'waiting_member', 'decided'));
update public.review_items set stage = 'decided' where status = 'closed' and stage <> 'decided';
alter table public.review_items add column if not exists assigned_to uuid references public.profiles (id) on delete set null;
alter table public.review_items add column if not exists other_id uuid references public.profiles (id) on delete set null;
alter table public.review_items add column if not exists subject_member_no bigint;
alter table public.review_items add column if not exists other_member_no bigint;

-- A case outlives a removed account: its subject goes, its record stays.
alter table public.review_items alter column subject_id drop not null;
alter table public.review_items drop constraint if exists review_items_subject_id_fkey;
alter table public.review_items add constraint review_items_subject_id_fkey
  foreign key (subject_id) references public.profiles (id) on delete set null;

create or replace function public.review_item_numbers()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.subject_id is not null and new.subject_member_no is null then
    select member_no into new.subject_member_no from profiles where id = new.subject_id;
  end if;
  if new.other_id is not null and new.other_member_no is null then
    select member_no into new.other_member_no from profiles where id = new.other_id;
  end if;
  return new;
end;
$$;
revoke all on function public.review_item_numbers() from public, anon, authenticated;
drop trigger if exists review_item_numbers on public.review_items;
create trigger review_item_numbers before insert or update of subject_id, other_id on public.review_items
  for each row execute function public.review_item_numbers();

-- The other member in a case: the reporter, or the other half of a date.
update public.review_items i set other_id = r.reporter_id
  from public.reports r where i.source_table = 'reports' and r.id = i.source_id and i.other_id is null;
update public.review_items i set other_id = case when d.member_a = i.subject_id then d.member_b else d.member_a end
  from public.date_commitments d where i.source_table = 'attendance_reviews' and d.id = i.source_id and i.other_id is null;
update public.review_items i set subject_member_no = p.member_no from public.profiles p where p.id = i.subject_id and i.subject_member_no is null;
update public.review_items i set other_member_no = p.member_no from public.profiles p where p.id = i.other_id and i.other_member_no is null;

create or replace function public._queue(p_kind text, p_subject uuid, p_table text, p_id uuid, p_other uuid)
returns void language sql security definer set search_path = public as $$
  insert into review_items (kind, subject_id, source_table, source_id, other_id)
  values (p_kind, p_subject, p_table, p_id, p_other)
  on conflict (source_table, source_id) do nothing;
$$;
revoke all on function public._queue(text, uuid, text, uuid, uuid) from public, anon, authenticated;

create or replace function public.queue_from_source()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_other uuid;
begin
  if tg_table_name = 'integrity_reviews' then
    perform _queue('pricing', new.profile_id, 'integrity_reviews', new.id, null);
  elsif tg_table_name = 'reports' then
    perform _queue(case when new.reason = 'user_is_married' then 'married_report'
                        when new.blind then 'blind_report' else 'report' end,
                   new.reported_id, 'reports', new.id, new.reporter_id);
  elsif tg_table_name = 'attendance_reviews' then
    select case when d.member_a = new.contested_by then d.member_b else d.member_a end into v_other
      from date_commitments d where d.id = new.commitment_id;
    perform _queue('attendance', new.contested_by, 'attendance_reviews', new.commitment_id, v_other);
  elsif tg_table_name = 'verification_sessions' then
    if new.status = 'attention' and (tg_op = 'INSERT' or old.status is distinct from 'attention') then
      perform _queue(case when new.product = 'smartselfie' then 'selfie_review' else 'id_review' end,
                     new.profile_id, 'verification_sessions', new.id, null);
    end if;
  end if;
  return new;
end;
$$;

-- What the case is about, in one plain sentence. Category words only:
-- never message text, never a reporter's name.
create or replace function public._report_label(p report_reason)
returns text language sql immutable as $$
  select case p
    when 'user_is_married' then 'Married'
    when 'scam_or_fraud' then 'Scam or fraud'
    when 'asked_for_money' then 'Asking for money'
    when 'fake_profile' then 'Fake profile'
    when 'harassment' then 'Harassment'
    when 'threats_or_coercion' then 'Threats or coercion'
    when 'underage' then 'Under 18'
    else 'Other' end;
$$;

create or replace function public._country_name(p text)
returns text language sql immutable as $$
  select case upper(coalesce(p, ''))
    when 'NG' then 'Nigeria' when 'GB' then 'the UK' when 'US' then 'the US' when 'CA' then 'Canada'
    when 'IE' then 'Ireland' when 'DE' then 'Germany' when 'NL' then 'the Netherlands' when 'ZA' then 'South Africa'
    when 'GH' then 'Ghana' when 'AE' then 'the UAE' when 'FR' then 'France' when 'IT' then 'Italy'
    when '' then 'an unknown country' else upper(p) end;
$$;

create or replace function public._case_reason(i review_items)
returns text language plpgsql stable security definer set search_path = public as $$
declare
  ir integrity_reviews;
  r reports;
  d date_commitments;
  vs verification_sessions;
  v_n integer;
  v_route text;
begin
  if i.kind = 'pricing' then
    select * into ir from integrity_reviews where id = i.source_id;
    v_route := ir.detail ->> 'route';
    return case ir.signal
      when 'profile_country_mismatch' then
        case when v_route = 'coin_pack' then 'Bought a naira coin pack while their profile says they live in ' || _country_name(ir.detail ->> 'country') || '.'
             when v_route = 'coins' then 'Paid for a naira plan with coins while their profile says they live in ' || _country_name(ir.detail ->> 'country') || '.'
             else 'Bought a naira plan while their profile says they live in ' || _country_name(ir.detail ->> 'country') || '.' end
      when 'payment_geography_mismatch' then 'Paid in naira with a card issued in ' || _country_name(ir.detail ->> 'country') || '.'
      when 'ip_country_mismatch' then 'Opened a naira checkout from ' || _country_name(ir.detail ->> 'country') || '.'
      else 'Pricing signal: ' || replace(ir.signal::text, '_', ' ') || '.' end;
  elsif i.kind in ('report', 'married_report', 'blind_report') then
    select * into r from reports where id = i.source_id;
    select count(*) into v_n from reports where reported_id = r.reported_id and created_at <= r.created_at and reason = r.reason;
    if i.kind = 'married_report' then
      return 'A match says this member is married. ' || case when v_n <= 1 then 'First report on the account.' else 'Report ' || v_n || ' of this kind on the account.' end;
    elsif i.kind = 'blind_report' then
      return 'Reported from a locked inbox as “' || _report_label(r.reason) || '”. The reporter hasn''t read the messages.';
    end if;
    return 'Reported as “' || _report_label(r.reason) || '”.' || case when v_n > 1 then ' Report ' || v_n || ' of this kind on the account.' else '' end;
  elsif i.kind = 'attendance' then
    select * into d from date_commitments where id = i.source_id;
    return 'Says they were at ' || coalesce(d.venue_name, 'the venue') || '. '
        || case when d.a_checked_in_at is not null and d.b_checked_in_at is not null then 'Both check-ins were recorded.'
                when d.a_checked_in_at is null and d.b_checked_in_at is null then 'No check-in was recorded.'
                else 'Only one check-in was recorded.' end;
  elsif i.kind in ('selfie_review', 'id_review') then
    select * into vs from verification_sessions where id = i.source_id;
    select count(*) into v_n from verification_sessions where profile_id = vs.profile_id and product = vs.product;
    return case when i.kind = 'selfie_review' then 'Selfie liveness came back for review' else 'ID check came back for review' end
        || case when v_n > 1 then ' after ' || (v_n - 1) || ' earlier attempt' || case when v_n > 2 then 's' else '' end || '.' else '.' end;
  elsif i.kind = 'photo_match' then
    return 'Main photo may not match the verified selfie.';
  end if;
  return 'Safety flag.';
end;
$$;
revoke all on function public._case_reason(review_items) from public, anon, authenticated;

-- "Adaeze O." from "Adaeze Okafor".
create or replace function public._staff_label(p uuid)
returns text language sql stable security definer set search_path = public as $$
  select coalesce(
    (select case when position(' ' in trim(display_name)) > 0
                 then split_part(trim(display_name), ' ', 1) || ' ' || left(reverse(split_part(reverse(trim(display_name)), ' ', 1)), 1) || '.'
                 else trim(display_name) end
       from profiles where id = p),
    'Staff');
$$;
revoke all on function public._staff_label(uuid) from public, anon, authenticated;

-- The case timeline: system and reviewer entries, never edited.
create table if not exists public.case_events (
  id uuid primary key default gen_random_uuid(),
  review_item_id uuid not null references public.review_items (id) on delete cascade,
  at timestamptz not null default now(),
  actor_id uuid references public.profiles (id) on delete set null,
  actor_label text not null,
  actor_role text not null,
  what text not null,
  why text check (char_length(why) <= 1000),
  is_decision boolean not null default false
);
create index if not exists case_events_item_idx on public.case_events (review_item_id, at);
alter table public.case_events enable row level security;
revoke all on public.case_events from anon, authenticated;

create or replace function public.case_events_append_only()
returns trigger language plpgsql as $$
begin
  raise exception 'Case history is append-only.' using errcode = '42501';
end;
$$;
drop trigger if exists case_events_append_only on public.case_events;
create trigger case_events_append_only before update on public.case_events
  for each row execute function public.case_events_append_only();
-- Deletes only by cascade from a case, and cases are never deleted.
create or replace function public.case_events_no_delete()
returns trigger language plpgsql as $$
begin
  if exists (select 1 from review_items where id = old.review_item_id) then
    raise exception 'Case history is append-only.' using errcode = '42501';
  end if;
  return old;
end;
$$;
drop trigger if exists case_events_no_delete on public.case_events;
create trigger case_events_no_delete before delete on public.case_events
  for each row execute function public.case_events_no_delete();

create or replace function public._case_event(p_item uuid, p_what text, p_why text, p_decision boolean default false)
returns void language sql security definer set search_path = public as $$
  insert into case_events (review_item_id, actor_id, actor_label, actor_role, what, why, is_decision)
  select p_item, s.profile_id, _staff_label(s.profile_id), s.role, p_what, left(p_why, 1000), p_decision
    from staff_members s where s.profile_id = auth.uid()
  union all
  select p_item, null, 'System', 'Automatic', p_what, left(p_why, 1000), p_decision
   where not exists (select 1 from staff_members where profile_id = auth.uid());
$$;
revoke all on function public._case_event(uuid, text, text, boolean) from public, anon, authenticated;

create or replace function public.case_raised()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into case_events (review_item_id, actor_label, actor_role, what, why)
  values (new.id, 'System', 'Automatic', 'Raised', _case_reason(new));
  return new;
end;
$$;
revoke all on function public.case_raised() from public, anon, authenticated;
drop trigger if exists case_raised on public.review_items;
create trigger case_raised after insert on public.review_items
  for each row execute function public.case_raised();

insert into case_events (review_item_id, at, actor_label, actor_role, what, why)
select i.id, i.created_at, 'System', 'Automatic', 'Raised', _case_reason(i) from review_items i
 where not exists (select 1 from case_events e where e.review_item_id = i.id);

-- The member responds: a fresh selfie passes, or they move to a Diaspora
-- plan, or they change their profile country to Nigeria.
create or replace function public.reverification_passed()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_n integer;
  i review_items;
begin
  if new.product = 'smartselfie' and new.passed is true and old.passed is distinct from true then
    delete from reverification_requests where profile_id = new.profile_id and requested_at <= new.created_at;
    get diagnostics v_n = row_count;
    if v_n > 0 then
      for i in select * from review_items where subject_id = new.profile_id and stage = 'waiting_member' loop
        insert into case_events (review_item_id, actor_label, actor_role, what, why)
        values (i.id, 'System', 'Automatic', 'Member responded', 'Selfie liveness passed.');
        update review_items set stage = case when assigned_to is null then 'new' else 'in_review' end where id = i.id;
      end loop;
    end if;
  end if;
  return new;
end;
$$;

create or replace function public.case_member_switched()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  i review_items;
begin
  if new.tier not in ('diaspora', 'diaspora_plus') or new.source <> 'subscription' then return new; end if;
  for i in select * from review_items where subject_id = new.profile_id and kind = 'pricing' and stage = 'waiting_member' loop
    insert into case_events (review_item_id, actor_label, actor_role, what, why)
    values (i.id, 'System', 'Automatic', 'Member responded', 'Moved to a Diaspora plan.'),
           (i.id, 'System', 'Automatic', 'Closed', 'Plan change completed.');
    update review_items set stage = 'decided', status = 'closed', decision = 'member_switched', decided_at = now() where id = i.id;
  end loop;
  return new;
end;
$$;
revoke all on function public.case_member_switched() from public, anon, authenticated;
drop trigger if exists case_member_switched on public.entitlements;
create trigger case_member_switched after insert on public.entitlements
  for each row execute function public.case_member_switched();

create or replace function public.case_country_changed()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  i review_items;
begin
  if new.country_code is not distinct from old.country_code or new.country_code <> 'NG' then return new; end if;
  for i in select * from review_items where subject_id = new.id and kind = 'pricing' and stage = 'waiting_member' loop
    insert into case_events (review_item_id, actor_label, actor_role, what, why)
    values (i.id, 'System', 'Automatic', 'Member responded', 'Changed their profile country to Nigeria.');
    update review_items set stage = case when assigned_to is null then 'new' else 'in_review' end where id = i.id;
  end loop;
  return new;
end;
$$;
revoke all on function public.case_country_changed() from public, anon, authenticated;
drop trigger if exists case_country_changed on public.profiles;
create trigger case_country_changed after update of country_code on public.profiles
  for each row execute function public.case_country_changed();

-- ---------------------------------------------------------------------------
-- Staff functions
-- ---------------------------------------------------------------------------

create or replace function public.staff_me()
returns jsonb language plpgsql stable security definer set search_path = public as $$
begin
  perform _require_staff();
  return (select jsonb_build_object('name', _staff_label(profile_id), 'role', role) from staff_members where profile_id = auth.uid());
end;
$$;

drop function if exists public.staff_queue(text, text);
create or replace function public.staff_queue(p_group text default 'open')
returns table (id uuid, case_no bigint, kind text, reason text, created_at timestamptz, stage text, assigned_name text)
language plpgsql stable security definer set search_path = public as $$
begin
  perform _require_staff();
  return query
  select i.id, i.case_no, i.kind, _case_reason(i), i.created_at, i.stage,
         case when i.assigned_to is null then null else _staff_label(i.assigned_to) end
    from review_items i
   where case p_group
           when 'open' then i.stage <> 'decided'
           when 'all' then true
           else i.stage = p_group end
   order by i.created_at asc
   limit 500;
end;
$$;

create or replace function public.staff_assign(p_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  perform _require_staff();
  update review_items set assigned_to = auth.uid(), stage = case when stage = 'new' then 'in_review' else stage end
   where id = p_id and stage <> 'decided';
  if not found then raise exception 'That case is already decided.' using errcode = '22023'; end if;
  perform _case_event(p_id, 'Assigned', 'Assigned to self.');
end;
$$;

-- One case: the facts the rules allow. Members appear by number, never by
-- name. Never message bodies, Gist content, genotype, or selfie/ID images
-- (Toastly keeps none of the last three; a constraint check holds the first).
create or replace function public.staff_item(p_id uuid)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  i review_items;
  ir integrity_reviews;
  r reports;
  d date_commitments;
  vs verification_sessions;
  v_evidence jsonb := '{}'::jsonb;
  v_actions jsonb;
  v_members jsonb := '[]'::jsonb;
begin
  perform _require_staff();
  select * into i from review_items where id = p_id;
  if not found then raise exception 'No such case.' using errcode = 'P0002'; end if;

  if i.kind = 'pricing' then
    select * into ir from integrity_reviews where id = i.source_id;
    v_evidence := jsonb_build_object(
      'signal', ir.signal, 'detail', ir.detail, 'raised_at', ir.created_at,
      'profile_country', (select country_code from profiles where id = i.subject_id),
      'profile_time_zone', (select time_zone from profiles where id = i.subject_id),
      'payments_90_days', (select coalesce(jsonb_agg(jsonb_build_object(
          'currency', x.currency, 'kind', x.kind, 'status', x.status, 'card_country', x.card_country,
          'request_country', x.ip_country, 'at', x.created_at) order by x.created_at desc), '[]'::jsonb)
        from payments x where x.profile_id = i.subject_id and x.created_at > now() - interval '90 days'));
  elsif i.kind in ('report', 'married_report', 'blind_report') then
    select * into r from reports where id = i.source_id;
    v_evidence := jsonb_build_object(
      'reason', _report_label(r.reason), 'reporter_note', r.detail, 'reported_at', r.created_at, 'blind', r.blind,
      'messages_from_member_to_reporter', (select count(*) from messages m join threads t on t.id = m.thread_id
          where m.sender_id = r.reported_id and (t.member_a = r.reporter_id or t.member_b = r.reporter_id)),
      'conversations_opened_9_days', (select count(*) from threads t
          where (t.member_a = r.reported_id or t.member_b = r.reported_id) and t.created_at > now() - interval '9 days'),
      'had_gist_together', exists (select 1 from gist_sessions g where (g.proposer_id = r.reporter_id and g.invitee_id = r.reported_id)
                                                           or (g.proposer_id = r.reported_id and g.invitee_id = r.reporter_id)));
  elsif i.kind = 'attendance' then
    select * into d from date_commitments where id = i.source_id;
    v_evidence := jsonb_build_object(
      'venue', d.venue_name, 'agreed_time', d.scheduled_for, 'stake_coins', d.stake_coins,
      'proposer_member_no', (select member_no from profiles where id = d.member_a),
      'other_member_no', (select member_no from profiles where id = d.member_b),
      'proposer_checked_in_at', d.a_checked_in_at, 'other_checked_in_at', d.b_checked_in_at,
      'contested_at', d.contested_at, 'status', d.status);
  elsif i.kind in ('selfie_review', 'id_review') then
    select * into vs from verification_sessions where id = i.source_id;
    v_evidence := jsonb_build_object(
      'product', vs.product, 'environment', vs.environment, 'result_code', vs.result_code, 'at', vs.created_at,
      'attempts', (select coalesce(jsonb_agg(jsonb_build_object('status', s.status, 'code', s.result_code, 'at', s.created_at)
                    order by s.created_at desc), '[]'::jsonb)
                   from verification_sessions s where s.profile_id = i.subject_id and s.product = vs.product));
  end if;

  -- The people in the case, by number, with what a reviewer needs to place
  -- them — plan, tenure, city, verification outcomes, report and date record.
  select coalesce(jsonb_agg(m order by m ->> 'order'), '[]'::jsonb) into v_members from (
    select jsonb_build_object(
      'order', x.ord, 'role', x.role, 'member_no', coalesce(p.member_no, x.no),
      'removed', p.id is null,
      'tier', case when p.id is null then null else current_tier(p.id) end,
      'joined', p.created_at, 'city', p.city, 'country', p.country_code,
      'phone_verified_at', p.phone_verified_at, 'liveness_verified_at', p.liveness_verified_at,
      'id_confirmed_at', p.id_confirmed_at,
      'id_type', (select id_type from verified_id_hashes h where h.profile_id = p.id),
      'reports_about', (select coalesce(jsonb_agg(jsonb_build_object('reason', _report_label(rr.reason), 'at', rr.created_at, 'status', rr.status)
                         order by rr.created_at desc), '[]'::jsonb) from reports rr where rr.reported_id = p.id),
      'earlier_cases', (select coalesce(jsonb_agg(jsonb_build_object('case_no', o.case_no, 'kind', o.kind, 'decision', o.decision)
                         order by o.created_at desc), '[]'::jsonb)
                        from review_items o where o.subject_id = p.id and o.id <> i.id),
      'dates', (select jsonb_build_object(
                  'attended', count(*) filter (where dc.status = 'completed'),
                  'missed', count(*) filter (where dc.status = 'no_show' and dc.no_show_member = p.id),
                  'cancelled', count(*) filter (where dc.status = 'cancelled'))
                from date_commitments dc where p.id in (dc.member_a, dc.member_b)),
      'restricted', p.id is not null and is_restricted(p.id)) as m
    from (values
      (1, case when i.kind in ('report', 'married_report', 'blind_report') then 'Reported member'
               when i.kind = 'attendance' then 'Member who contested' else 'Member' end, i.subject_id, i.subject_member_no),
      (2, case when i.kind = 'attendance' then 'Other member' else 'Reporter' end, i.other_id, i.other_member_no)
    ) as x(ord, role, pid, no)
    left join profiles p on p.id = x.pid
    where x.pid is not null or x.no is not null
  ) s;

  v_actions := case
    when i.stage = 'decided' then '[]'::jsonb
    when i.kind = 'attendance' then '["attended", "no_show", "restrict", "remove"]'::jsonb
    when i.kind = 'pricing' then '["clear", "ask_switch_plan", "request_reverification", "restrict", "remove"]'::jsonb
    else '["clear", "request_reverification", "restrict", "remove"]'::jsonb end;
  if i.subject_id is null then
    v_actions := '[]'::jsonb;
  elsif is_restricted(i.subject_id) then
    v_actions := (v_actions - 'restrict') || '["lift_restriction"]'::jsonb;
  end if;

  return jsonb_build_object(
    'id', i.id, 'case_no', i.case_no, 'kind', i.kind, 'stage', i.stage, 'status', i.status, 'decision', i.decision,
    'created_at', i.created_at, 'decided_at', i.decided_at, 'reason', _case_reason(i),
    'reason_category', _reason_category(i.kind),
    'assigned_name', case when i.assigned_to is null then null else _staff_label(i.assigned_to) end,
    'assigned_to_me', i.assigned_to = auth.uid(),
    'subject', jsonb_build_object('id', i.subject_id, 'member_no', i.subject_member_no),
    'members', v_members,
    'evidence', v_evidence,
    'events', (select coalesce(jsonb_agg(jsonb_build_object('at', e.at, 'who', e.actor_label, 'role', e.actor_role,
                 'what', e.what, 'why', e.why, 'decision', e.is_decision) order by e.at), '[]'::jsonb)
               from case_events e where e.review_item_id = i.id),
    'actions', v_actions);
end;
$$;

-- Decide a case. A written reason is required for every action.
create or replace function public.staff_decide(p_id uuid, p_action text, p_note text default null)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  i review_items;
  v_cat text;
  v_allowed jsonb;
  v_label text;
begin
  perform _require_staff();
  if char_length(trim(coalesce(p_note, ''))) < 12 then
    raise exception 'Write the reason for this decision — a short sentence is enough.' using errcode = '22023';
  end if;
  select * into i from review_items where id = p_id for update;
  if not found then raise exception 'No such case.' using errcode = 'P0002'; end if;
  v_allowed := staff_item(p_id) -> 'actions';
  if not (v_allowed ? p_action) then
    raise exception 'That action isn''t available for this case.' using errcode = '22023';
  end if;
  v_cat := _reason_category(i.kind);
  v_label := case p_action
    when 'clear' then 'Clear' when 'ask_switch_plan' then 'Ask to switch plan'
    when 'request_reverification' then 'Request re-verification' when 'restrict' then 'Restrict'
    when 'lift_restriction' then 'Lift restriction' when 'remove' then 'Remove'
    when 'attended' then 'Attended — both stakes back' when 'no_show' then 'Didn''t attend — stake to the attender'
    else p_action end;

  -- Written first, so even a removal leaves its record.
  insert into staff_audit_log (staff_id, review_item_id, item_kind, subject_id, action, reason_category, note)
  values (auth.uid(), i.id, i.kind, i.subject_id, p_action, v_cat, left(p_note, 1000));
  perform _case_event(i.id, v_label, p_note, true);

  if p_action = 'lift_restriction' then
    update account_restrictions set lifted_at = now(), lifted_by = auth.uid()
     where profile_id = i.subject_id and lifted_at is null;
    return jsonb_build_object('action', p_action, 'subject_id', i.subject_id, 'reason_category', v_cat);
  end if;

  if p_action in ('ask_switch_plan', 'request_reverification') then
    update review_items set stage = 'waiting_member', assigned_to = coalesce(assigned_to, auth.uid()),
                            decision = p_action, decided_by = auth.uid(), decided_at = now()
     where id = i.id;
  else
    update review_items set stage = 'decided', status = 'closed', decision = p_action, decided_by = auth.uid(),
                            decided_at = now(), assigned_to = coalesce(assigned_to, auth.uid())
     where id = i.id;
  end if;

  if p_action = 'clear' then
    perform _close_source(i, true);
  elsif p_action = 'ask_switch_plan' then
    insert into member_notices (profile_id, kind, reason_category) values (i.subject_id, 'switch_plan', v_cat);
    perform _close_source(i, false);
  elsif p_action = 'request_reverification' then
    insert into reverification_requests (profile_id, reason_category, requested_by)
    values (i.subject_id, v_cat, auth.uid())
    on conflict (profile_id) do update set reason_category = excluded.reason_category, requested_at = now(), requested_by = excluded.requested_by;
    perform _close_source(i, false);
  elsif p_action = 'restrict' then
    insert into account_restrictions (profile_id, reason_category, review_item_id, created_by)
    values (i.subject_id, v_cat, i.id, auth.uid());
    perform _close_source(i, false);
  elsif p_action in ('attended', 'no_show') then
    perform resolve_attendance_review(i.source_id, p_action = 'attended');
  elsif p_action = 'remove' then
    perform _close_source(i, false);
    perform _remove_account(i.subject_id, v_cat);
  end if;

  return jsonb_build_object('action', p_action, 'subject_id', i.subject_id, 'reason_category', v_cat);
end;
$$;

-- Decision history: find a case by case number (TC-20418 / 20418) or
-- member number (M-40012 / 40012). Read-only.
create or replace function public.staff_history(p_q text default null)
returns table (id uuid, case_no bigint, kind text, stage text, decision text, subject_member_no bigint,
               other_member_no bigint, last_at timestamptz)
language plpgsql stable security definer set search_path = public as $$
declare
  v_n bigint := nullif(regexp_replace(coalesce(p_q, ''), '\D', '', 'g'), '')::bigint;
begin
  perform _require_staff();
  return query
  select i.id, i.case_no, i.kind, i.stage, i.decision, i.subject_member_no, i.other_member_no,
         (select max(e.at) from case_events e where e.review_item_id = i.id)
    from review_items i
   where v_n is null or i.case_no = v_n or i.subject_member_no = v_n or i.other_member_no = v_n
   order by 8 desc nulls last
   limit 100;
end;
$$;

revoke all on function public.staff_me() from public, anon;
revoke all on function public.staff_queue(text) from public, anon;
revoke all on function public.staff_assign(uuid) from public, anon;
revoke all on function public.staff_item(uuid) from public, anon;
revoke all on function public.staff_decide(uuid, text, text) from public, anon;
revoke all on function public.staff_history(text) from public, anon;
grant execute on function public.staff_me() to authenticated;
grant execute on function public.staff_queue(text) to authenticated;
grant execute on function public.staff_assign(uuid) to authenticated;
grant execute on function public.staff_item(uuid) to authenticated;
grant execute on function public.staff_decide(uuid, text, text) to authenticated;
grant execute on function public.staff_history(text) to authenticated;
